import React from 'react';
import PropTypes from 'prop-types';
import Head from "next/head";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Login from "../auth/Login";
import PasswordReset from "../auth/PasswordReset";

const Layout = (props: {title: string, children: any}) => {
    const {title, children} = props;

    return (
        <>
            <Head>
                <title>{title && `${title} | `}BNB</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar/>
            <main>
                {children}
            </main>
            <Footer/>

            {/* global modals */}
            <Login/>
            <PasswordReset/>
        </>
    );
};

Layout.propTypes = {
    title: PropTypes.string.isRequired,
};

export default Layout;